# Numpy Liberaries

In [1]:
import numpy as np

In [2]:
import time

n = 1_000

start = time.perf_counter()

total = 0
for i in range(n):
    total += i * i

end = time.perf_counter()
print(total)
#print("Python loop time:", end - start)
import time

n = 1_000

start = time.perf_counter()

arr = np.arange(n)
total = np.sum(arr * arr)

end = time.perf_counter()
print(total)
#print("NumPy vectorized time:", end - start)


332833500
332833500


In [3]:
myarr = np.array([89,78,99,22], np.int8) # np.int here shows 8 bit integer

In [4]:
myarr

array([89, 78, 99, 22], dtype=int8)

In [5]:
arr = np.array([[52,11,89,224]],np.int64)

In [6]:
arr

array([[ 52,  11,  89, 224]])

In [7]:
print(arr.dtype)

int64


In [8]:
print(myarr[2]) # 1 Dimenstional array print

99


In [9]:
print(arr[0,2]) # used to print 2 Dimenstional Array

89


In [10]:
myarr.shape # used to print shape of array

(4,)

In [11]:
arr.shape

(1, 4)

In [12]:
myarr[1]=44

In [13]:
arr[0,2]=38

In [14]:
myarr

array([89, 44, 99, 22], dtype=int8)

In [15]:
arr

array([[ 52,  11,  38, 224]])

In [16]:
array = np.array([[3,5,6],[66,45,77],[23,78,90]])

In [17]:
array

array([[ 3,  5,  6],
       [66, 45, 77],
       [23, 78, 90]])

In [18]:
array.size

9

In [19]:
array.shape

(3, 3)

In [20]:
array.dtype

dtype('int64')

In [21]:
array[2,1]=55

In [22]:
array

array([[ 3,  5,  6],
       [66, 45, 77],
       [23, 55, 90]])

In [24]:
zero_array= np.zeros((2,3)) # used to create array of zero element

In [25]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
iden= np.identity(3) # used to create identity matrix

In [30]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arrange= np.arange(30) # used to create array of range

In [33]:
arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])