# Numpy Liberaries

In [1]:
import numpy as np

In [2]:
import time

n = 1_000

start = time.perf_counter()

total = 0
for i in range(n):
    total += i * i

end = time.perf_counter()
print(total)
#print("Python loop time:", end - start)
import time

n = 1_000

start = time.perf_counter()

arr = np.arange(n)
total = np.sum(arr * arr)

end = time.perf_counter()
print(total)
#print("NumPy vectorized time:", end - start)


332833500
332833500


In [3]:
myarr = np.array([89,78,99,22], np.int8) # np.int here shows 8 bit integer

In [4]:
myarr

array([89, 78, 99, 22], dtype=int8)

In [5]:
arr = np.array([[52,11,89,224]],np.int64)

In [6]:
arr

array([[ 52,  11,  89, 224]])

In [7]:
print(arr.dtype)

int64


In [8]:
print(myarr[2]) # 1 Dimenstional array print

99


In [9]:
print(arr[0,2]) # used to print 2 Dimenstional Array

89


In [10]:
myarr.shape # used to print shape of array

(4,)

In [11]:
arr.shape

(1, 4)

In [12]:
myarr[1]=44

In [13]:
arr[0,2]=38

In [14]:
myarr

array([89, 44, 99, 22], dtype=int8)

In [15]:
arr

array([[ 52,  11,  38, 224]])

In [16]:
array = np.array([[3,5,6],[66,45,77],[23,78,90]])

In [17]:
array

array([[ 3,  5,  6],
       [66, 45, 77],
       [23, 78, 90]])

In [18]:
array.size

9

In [19]:
array.shape

(3, 3)

In [20]:
array.dtype

dtype('int64')

In [21]:
array[2,1]=55

In [22]:
array

array([[ 3,  5,  6],
       [66, 45, 77],
       [23, 55, 90]])

In [23]:
zero_array= np.zeros((2,3)) # used to create array of zero element

In [24]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
iden= np.identity(3) # used to create identity matrix

In [26]:
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arrange= np.arange(30) # used to create array of range

In [28]:
arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
lspace=np.linspace(1,10,19) # equal space element

In [30]:
lspace

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [31]:
aa= np.arange(66)

In [32]:
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [33]:
aa = aa.reshape(3,22)

In [34]:
aa

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
        60, 61, 62, 63, 64, 65]])

In [35]:
aa.sum(axis=0) # sum of x axis

array([ 66,  69,  72,  75,  78,  81,  84,  87,  90,  93,  96,  99, 102,
       105, 108, 111, 114, 117, 120, 123, 126, 129])

In [36]:
aa.sum(axis=1) # sum of y axis

array([ 231,  715, 1199])

In [37]:
aa.T # used to transpose

array([[ 0, 22, 44],
       [ 1, 23, 45],
       [ 2, 24, 46],
       [ 3, 25, 47],
       [ 4, 26, 48],
       [ 5, 27, 49],
       [ 6, 28, 50],
       [ 7, 29, 51],
       [ 8, 30, 52],
       [ 9, 31, 53],
       [10, 32, 54],
       [11, 33, 55],
       [12, 34, 56],
       [13, 35, 57],
       [14, 36, 58],
       [15, 37, 59],
       [16, 38, 60],
       [17, 39, 61],
       [18, 40, 62],
       [19, 41, 63],
       [20, 42, 64],
       [21, 43, 65]])

array([[ 0, 22, 44],
       [ 1, 23, 45],
       [ 2, 24, 46],
       [ 3, 25, 47],
       [ 4, 26, 48],
       [ 5, 27, 49],
       [ 6, 28, 50],
       [ 7, 29, 51],
       [ 8, 30, 52],
       [ 9, 31, 53],
       [10, 32, 54],
       [11, 33, 55],
       [12, 34, 56],
       [13, 35, 57],
       [14, 36, 58],
       [15, 37, 59],
       [16, 38, 60],
       [17, 39, 61],
       [18, 40, 62],
       [19, 41, 63],
       [20, 42, 64],
       [21, 43, 65]])

In [39]:
for item in array:
    print(item)

[3 5 6]
[66 45 77]
[23 55 90]


In [40]:
array.ndim # array dimension

2

In [41]:
aa.nbytes # total bytes consumed

528

In [43]:
array.argmax() # index of maximum value

np.int64(8)

In [45]:
array.argmin()

np.int64(0)

In [46]:
array.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2]])

In [47]:
array.argmax(axis=0)

array([1, 2, 2])

In [48]:
z=np.array([[44,22,43],[78,78,99],[22,32,44]])

In [49]:
array+z

array([[ 47,  27,  49],
       [144, 123, 176],
       [ 45,  87, 134]])

In [50]:
array*z

array([[ 132,  110,  258],
       [5148, 3510, 7623],
       [ 506, 1760, 3960]])

In [51]:
array-z

array([[-41, -17, -37],
       [-12, -33, -22],
       [  1,  23,  46]])

In [53]:
np.sqrt(array)

array([[1.73205081, 2.23606798, 2.44948974],
       [8.1240384 , 6.70820393, 8.77496439],
       [4.79583152, 7.41619849, 9.48683298]])

In [55]:
array.sum()

np.int64(370)

In [56]:
array.max()

np.int64(90)

In [57]:
np.where(array>50)

(array([1, 1, 2, 2]), array([0, 2, 1, 2]))

In [59]:
np.nonzero(iden)

(array([0, 1, 2]), array([0, 1, 2]))